# Generated by Django 3.2.8 on 2021-11-03 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_business_owner',
            field=models.BooleanField(default=False),
        ),
    ]
